bikingfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from travel import views as a
from accounts import views as acc

#--------------------- imports for passsword rest ------------------------------------
from django.contrib.auth import views as auth_views
#--------------------- imports for passsword rest ------------------------------------
urlpatterns = [

#=========================Route for front End=======================================
#=========================Route for front End=======================================
#=========================Route for front End=======================================
    path('', a.FrontIndexPageView, name="frontendhome"),
    path('contact_us/', a.ContactUsPage, name="contactus"),
    path('about_us/', a.AboutusPage, name="aboutus"),
    #--------------------route for blog-------------------------------------------
    path('bloglist/', a.BlogsPage, name="bloglist"),
    path('detail_blog/<str:pk>', a.BlogDetailPage, name="blogdetails"),
    #---------------------Route for Packages category----------------------------
    path('packages_category/<str:pk>', a.PackageCategory, name="packagescategory"),
    path('packages_details/<str:pk>', a.PackageDetails, name="packagesdetails"),
    path('all_packages/', a.Allpackages, name="allpackages"),
    #-----------------------Route for booking packages--------------------------
    path('booking_packages/<str:pk>', a.BookingPack, name="bookingpackages"),
    #-----------------------Route for user login --------------------------------
    path('userlogin/', a.UserLogin, name="userlogin"),
    path('userloginprocess/', a.UserloginProcess, name="userloginprocess"),
    path('userlogoutprocess/', a.UserlogoutProcess, name="userlogoutprocess"),
    #-----------------------Route for user registration packages------------------------------
    path('usersignup/', a.UserRegistration, name="signupuser"),
    #-----------------------Route for search packages------------------------------
    path('packagessearch/',a.Searchpack, name="searchpackages"),

    #-------------------------ROute for user Profile------------------------------
    path('userprofile/', a.UserProfile, name="userprofile"),
    path('update_profile/', a.UserProfileUpdate, name="updateuserprofile"),
    path('my_pack/', a.MyPackView, name="mypack"),


#=========================Route for Back End =======================================
#=========================Route for Back End =======================================
#=========================Route for Back End =======================================


    path('admin/', a.BackEndLogin, name="loginpage"),
    path('loginprocess/',a.LoginProcess, name="loginprocess"),
    path('logoutprocess/',a.logoutprocess, name="logoutprocess"),
    path('dashboard/', a.BackEndPageView, name="backenddashbaord"),
#-----------------------Route for category-------------------------------------------
    path('add_category/',a.AddCategory, name="addcategory"),
    path('category_list/',a.CategorylistView, name="categorylist"),
    path('delete_category/<str:pk>',a.DeleteCategoryView, name="deletecategory"),
    path('update_category/<str:pk>',a.UpdatecategoryView, name="updatecategory"),

#-----------------------Route for sub category-------------------------------------------
    path('add_sub_category/',a.AddSubCategoryView, name="addsubcategory"),
    path('sub_category_list/',a.SubCategoryListView, name="subcategorylist"),
    path('delete_sub_category/<str:pk>',a.DeleteSubCateogryView, name="deletesubcateogry"),
    path('update_sub_category/<str:pk>',a.UpdateSubCategoryView, name="updatesubcateogry"),

#-----------------------Route for all category--------------------------------------------- 
    path('add_all_category/',a.AddAllCategoryView, name="addallcategory"),
    path('all_category_list/',a.allCategoryListView, name="allcategorylist"),
    path('delete_all_category/<str:pk>',a.DeleteSAllCateogryView, name="deleteallcategory"),
    path('update_all_category/<str:pk>',a.UpdateallCategoryView, name="updateallcategory"),

#-----------------------Route for Inclusion--------------------------------------------- 
    path('add_inclusion/',a.AddAllInslucionView, name="addinclusion"),
    path('inclusion_list/',a.InslucionListView, name="inclusionlist"),
    path('delete_inclusion/<str:pk>',a.DeleteSInclusionView, name="deleteinclusion"),
    path('update_inclusion/<str:pk>',a.UpdateInclusionView, name="updateinclusion"),

#-----------------------Route for Blogs--------------------------------------------- 

    path('add_blog/',a.AddBlogsView, name="addblogs"),
    path('blogs_list/',a.BlogsListView, name="blogslist"),
    path('delete_blogs/<str:pk>',a.DeleteSBlogsView, name="deleteblogs"),
    path('update_blogs/<str:pk>',a.UpdateBlogsView, name="updateblogs"),

#-----------------------Route for imageslider--------------------------------------------- 

    path('add_imageslider/',a.AddSliderImgView, name="addimageslider"),
    path('imageslider_list/',a.SliderImgListView, name="imagesliderlist"),
    path('delete_imageslider/<str:pk>',a.DeleteSLiderImgView, name="deleteimageslider"),
    path('update_imageslider/<str:pk>',a.UpdateSliderImgView, name="updateimageslider"),


#-----------------------Route for aboutus--------------------------------------------- 
    path('add_aboutus/',a.AddAboutusVIew, name="addaboutus"),
    path('aboutus_list/',a.AboutusList, name="aboutuslist"),
    path('delete_aboutus/<str:pk>',a.DeleteAboutusView, name="deleteaboutus"),
    path('update_aboutus/<str:pk>',a.UpdateAboutusView, name="updateaboutus"),


#-----------------------Route for contact detials--------------------------------------------- 
    path('add_contactdetails/',a.AddContactView, name="addcontactdetails"),
    path('contact_list/',a.ContactusList, name="contactdetailslist"),
    path('delete_contact/<str:pk>',a.DeleteContactus, name="deletecontactdetails"),
    path('update_contact/<str:pk>',a.UpdateContactusview, name="updatecontactdetails"),

#-----------------------Route for Packages--------------------------------------------- 
    path('add_packages/',a.AddPackagesView, name="addpackages"),
    path('packages_list/',a.PackagesList, name="packageslist"),
    path('delete_packages/<str:pk>',a.Deletepackages, name="deletepackages"),
    path('update_packages/<str:pk>',a.UpdatePakagesview, name="updatepackages"),
    
#-----------------------Route for booked packages-----------------------------------
    path('list_of_booked_packages', a.BookingPackagesList, name="bookedpackages"),
    path('details_of_booked_packages/<str:pk>', a.BookingDetails, name="detailsbookedpackages"),
#-----------------------Route for admin/user listing-----------------------------------

    path('admin_user/', a.ListingAdminUser, name="adminlisting"),
    path('normal_user/', a.ListingNormalUser, name="normaluser"),

#---------------------Route for inquirylist---------------------------------------------
    path('inquirylist/', a.InquiryList, name="inquirylist"),
    path('inquirylist/<str:pk>', a.InquirylistDetail, name="inquirylistdetail"),

#--------------------ROute for change password----------------------------------------------
    path('changepassword/', acc.AdminPasswordChangeView, name="AdminPasswordChangeView"),


#===================================================================================================================
#===================================================================================================================
#===================================================================================================================
#===================================================================================================================

#---------------------------- Route for password rest for user-----------------------------------------------------
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_complete"),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel/models.py
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
from accounts.models import user

# MODELS FOR CATEGORY SUB CATEGORY & ALL CATEGORY

#MODELS FOR CATEGORY
class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.title
    
#MODELS FOR SUB CATEGORY
class SubCategory(models.Model):
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.title


#MODELS FOR ALL CATEGORY
class AllCategory(models.Model):
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    sub_category = models.ForeignKey("SubCategory", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.title


#MODELS FOR INCLUSION
class Inclusion(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.title


#MODELS FOR BLOGS
class Blogs(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500)
    content = RichTextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    cover_image = models.FileField(upload_to="blogs_images", null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.title

    
#MODELS FOR IMAGE SLIDER
class SliderImage(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True)
    image = models.FileField( upload_to="slider_image")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


#MODELS FOR CONTACT DETAILS
class ContactDetail(models.Model):
    sub_title = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    mobile = models.CharField(max_length=15)
    email = models.EmailField()
    website = models.URLField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.slagon

#MODELS FOR ABOUT DETAILS
class AboutusDetail(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    about_cover = models.FileField(upload_to="about_cover_image")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


#MODELS FOR PACKAGES
RATING = (
    ('1','ONE'),
    ('2','TWO'),
    ('3','THREE'),
    ('4','FOUR'),
    ('5','FIVE'),
)
class Packages(models.Model):
    title = models.CharField(max_length=255)
    description = RichTextField()
    image = models.FileField(upload_to="trip_photos")
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    all_category = models.ForeignKey(AllCategory, on_delete=models.CASCADE)
    Itinerary = RichTextField()
    region = models.CharField(max_length=255)
    duration = models.CharField(max_length=255)
    starting_date = models.DateField()
    ending_date = models.DateField()
    Availability = models.BooleanField(default=False)
    inclusion  = models.ManyToManyField(Inclusion, related_name="package_inclusion", blank=True)
    price = models.PositiveIntegerField()
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class PackagesGallary(models.Model):
    packages = models.ForeignKey(Packages, on_delete=models.CASCADE)
    image = models.FileField(upload_to="packages/images")

    def __str__(self):
        return self.packages.title

#==============================================models for booking=======================================================
    
class BookPackages(models.Model):
    package = models.ForeignKey(Packages, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.IntegerField()
    email = models.EmailField()
    country = models.CharField(max_length=255)
    no_of_adults = models.CharField(max_length=255)
    no_of_children = models.CharField(max_length=255)
    created_by = models.ForeignKey(user, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.title 

    

class GenralInquery(models.Model):
    name = models.CharField(max_length=255)
    mobile = models.BigIntegerField()
    email = models.EmailField()
    subject = models.CharField(max_length=500)
    city = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.name


RATE_CHOICES = [

    ('1','Very bad'),
    ('2','Bad'),
    ('3','Good'),
    ('4','Very good'),
    ('5','Excellent'),
]

class Review(models.Model):
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    packages = models.ForeignKey(Packages, on_delete=models.CASCADE)
    comment = models.TextField(max_length=3000, blank=True)
    rate = models.CharField(max_length=255, choices=RATE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.id

templates/site/category/packdetail.html
{% extends 'site/partials/layout.html' %}


{% block title %}
{{ i.title }}
{% endblock title %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
{% include 'site/partials/header.html' %}
{% endblock header %}

{% block slider %}

	<section>
		<div class="rows inner_banner" style="background: url('{{ i.image.url }}') no-repeat center center;
     background-size: cover;">
			<div class="container">
				<h2 class="text-uppercase"><span>{{ i.title }}</span></h2>
				<ul>
					<li><a href="{% url 'frontendhome' %}">Home</a>
					</li>
					<li><i class="fa fa-angle-right" aria-hidden="true"></i> </li>
					<li><a href="#inner-page-title" class="bread-acti">{{ i.title }}</a>
					</li>
				</ul>				
			</div>
		</div>
	</section>
	<!--====== TOUR DETAILS - BOOKING ==========-->
	<section>
		<div class="rows banner_book" id="inner-page-title">
			<div class="container">
				<div class="banner_book_1">
					<ul>
						<li class="dl1">Region : {{ i.region }}</li>
						<li class="dl2">Price : ${{ i.price }}</li>
						<li class="dl3">Duration : {{ i.duration }}</li>
						{% if request.user.is_authenticated %}
						<li class="dl4"><a href="{% url 'bookingpackages' i.id %}">Book Now</a> </li>
						{% else %}
						<li class="dl4"><a href="{% url 'userlogin' %}"></a> </li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>
	</section>
	<!--====== TOUR DETAILS ==========-->
	<section>
		<div class="rows inn-page-bg com-colo">
			<div class="container inn-page-con-bg tb-space">
				<div class="col-md-9">
					<!--====== TOUR TITLE ==========-->
					<div class="tour_head">
						<h2>{{ i.title }}<span class="tour_star"><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-half-o" aria-hidden="true"></i></span><span class="tour_rat">4.5</span></h2> </div>
					<!--====== TOUR DESCRIPTION ==========-->
					<div class="tour_head1">
						<h3>Introduction</h3>
						<p>{{ i.description|safe  }}</p>
					</div>
					<!--====== ROOMS: HOTEL BOOKING ==========-->
					<div class="tour_head1 hotel-book-room">
						<h3>Photo Gallery</h3>
						<div id="myCarouse1" class="carousel slide" data-ride="carousel">
							<!-- Indicators -->
							<ol class="carousel-indicators carousel-indicators-1">
							{% for pi in i.packagesgallary_set.all %}
								<li data-target="#myCarousel1" data-slide-to="0"><img src="{{ pi.image.url }}" alt="{{ i.title }}">
								</li>
							{% endfor %}
							</ol>
							<div class="carousel-inner carousel-inner1" role="listbox">
							
								<div class="item active">
								<img src="{{ i.image.url }}" alt="Chania" width="460" height="345"> 
								</div>
							
							</div>
							
							<!-- Left and right controls -->
							<a class="left carousel-control" href="#myCarousel1" role="button" data-slide="prev"> <span><i class="fa fa-angle-left hotel-gal-arr" aria-hidden="true"></i></span> </a>
							<a class="right carousel-control" href="#myCarousel1" role="button" data-slide="next"> <span><i class="fa fa-angle-right hotel-gal-arr hotel-gal-arr1" aria-hidden="true"></i></span> </a>
						</div>
						
					</div>
										
					<!--====== DURATION ==========-->
					<div class="tour_head1 l-info-pack-days days">
						<h3>Detailed Itinerary</h3>
						<p>{{ i.Itinerary|safe }}</p>
					</div>
                    
                    {% comment %} <!--====== ABOUT THE TOUR ==========-->
					<div class="tour_head1">
						<h3>Dates & Prices</h3>
						<table>
							<tr>
								<th>Dates</th>
								<th class="event-res">Availability</th>
								<th class="event-res">Prices</th>
								<th>Book</th>
							</tr>
							<tr>
								<td>August 15 2021</td>
								<td class="event-res">Available</td>
								<td class="event-res">1600 Euros</td>
								<td><a href="booking.html" class="link-btn">Book Now</a> </td>
							</tr>
							<tr>
								<td>August 15 2021</td>
								<td class="event-res">Available</td>
								<td class="event-res">1600 Euros</td>
								<td><a href="booking.html" class="link-btn">Book Now</a> </td>
							</tr>
							<tr>
								<td>August 15 2021</td>
								<td class="event-res">Available</td>
								<td class="event-res">1600 Euros</td>
								<td><a href="booking.html" class="link-btn">Book Now</a> </td>
							</tr>
							<tr>
								<td>August 15 2021</td>
								<td class="event-res">Available</td>
								<td class="event-res">1600 Euros</td>
								<td><a href="#" class="link-btn">Book Now</a> </td>
							</tr>
						</table>
					</div> {% endcomment %}
					<div>						
					</div>
				</div>
				<div class="col-md-3 tour_r">					
					<!--====== TRIP INFORMATION ==========-->
					<div class="tour_right tour_incl tour-ri-com">
						<h3>Trip Inclusion</h3>
						<ul>
                        {% for a in i.inclusion.all %}
							<li>{{ a.title }}</li>
							
                        {% endfor %}
						</ul>
					</div>
					<!--====== PACKAGE SHARE ==========-->
					<div class="tour_right head_right tour_social tour-ri-com">
						<h3>Share This Package</h3>
						<ul>
							<li><a href="https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1:8000/packages_details/{{i.id}}" target="_blank" rel="nofollow"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="https://plus.google.com/share?url=http://127.0.0.1:8000/packages_details/{{i.id}}"target="_blank" rel="nofollow"><i class="fa fa-google-plus" aria-hidden="true"></i></a> </li>
							<li><a href="https://twitter.com/share?url=http://127.0.0.1:8000/packages_details/{{i.id}}"target="_blank" rel="nofollow"><i class="fa fa-twitter" aria-hidden="true"></i></a> </li>
							<li><a href="https://www.linkedin.com/shareArticle?mini=true&url=http://127.0.0.1:8000/packages_details/{{i.id}}"target="_blank" rel="nofollow"><i class="fa fa-linkedin" aria-hidden="true"></i></a> </li>
							<li><a href="https://wa.me/?text=http://127.0.0.1:8000/packages_details/{{i.id}}"><i class="fa fa-whatsapp" aria-hidden="true"></i></a> </li>
						</ul>
					</div>
					<!--====== HELP PACKAGE ==========-->
                    {% for i in contactlist %}
					<div class="tour_right head_right tour_help tour-ri-com">
						<h3>Help & Support</h3>
						<div class="tour_help_1">
							<h4 class="tour_help_1_call">Call Us Now</h4>
							<h4><i class="fa fa-phone" aria-hidden="true"></i> {{ i.phone }}</h4> </div>
					</div>
                    {% endfor %}
					<!--====== PUPULAR TOUR PACKAGES ==========-->
					<div class="tour_right tour_rela tour-ri-com">
						<h3>Similar Packages</h3>
						{% for simpack in simliar_package %}
						<div class="tour_rela_1"> <img src="{{ simpack.image.url }}" alt="" />
							<h4>{{ simpack.title }}</h4>
							<p>{{ simpack.description|safe|truncatechars:100}}</p> <a href="{% url 'packagesdetails' simpack.id %}" class="link-btn">View Detail</a> </div>						
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	
{% endblock slider %}
    
{% block footer %}
{% include 'site/partials/footer.html' %}
{% endblock footer %}

{% block script %}
{% include 'site/partials/script.html' %}
{% endblock script %}